version: "3.3"
services:
  mysql:
    image: bitnami/mariadb:latest
    container_name: StadiumTrackerDB
    volumes:
      - .\docker\mysql\data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=test
      - MARIADB_DATABASE=testdb
      - MARIADB_PASSWORD=test
  laravel-app:
    tty: true
    image: 'bitnami/laravel:latest'
    container_name: StadiumTrackerApp
    user: root
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=test
      - DB_DATABASE=testdb
      - DB_PASSWORD=test
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./:/app
